
twist_mux:
  ros__parameters:
    topics:
      joy:
        topic   : joy_teleop/cmd_vel
        timeout : 0.5
        priority: 10
      vision_safe:
        topic   : cmd_vel_vision_safe
        timeout : 0.5
        priority: 5
      external:
        topic   : cmd_vel
        timeout : 0.5
        priority: 1
    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255