controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tbot_velocity_controller:
      type: diff_drive_controller/DiffDriveController

tbot_velocity_controller:
  ros__parameters:    
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.186
    wheel_radius: 0.033

    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: false

    use_stamped_vel: false